upstream backend {
    # Dzięki sieci lab-network, Nginx rozwiąże 'backend' na IP kontenera Node.js
    server backend:3000;
}

server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Obsługa SPA - kieruj wszystko na index.html
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # Trailing slash na końcu usuwa '/api' z urla trafiającego do Node'a
        proxy_pass http://backend/;

        # Dodanie CORS
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS' always;
        add_header X-Cache-Status $upstream_cache_status always;

        # Konfiguracja Cache
        proxy_cache api_cache;
        proxy_cache_valid 200 30s;
        proxy_cache_use_stale error timeout;
        
        # Ograniczenie przepustowości 
        limit_rate 200k;

        # Opcjonalne, ale zalecane nagłówki dla zachowania kontekstu klienta
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}