events {}
http {
    upstream backend_srv { server backend:3000; }
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /api/ {
            proxy_pass http://backend_srv/;
            # To pozwoli nam zobaczyć nagłówek X-Cache z backendu
            proxy_pass_header X-Cache;
        }
    }
}