events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    proxy_cache_path /var/cache/nginx keys_zone=api_cache:10m;

    server {
        listen 80;
        root /usr/share/nginx/html;

        # Frontend SPA fallback
        location / {
            try_files $uri /index.html;
        }

        # API Proxy z Cache dla /stats
        location /api/stats {
            proxy_cache api_cache;
            proxy_cache_valid 200 30s;
            add_header X-Cache-Status $upstream_cache_status;
            proxy_pass http://backend:3000/stats;
        }

        # Standardowe API Proxy
        location /api/ {
            proxy_pass http://backend:3000/;
        }
    }
}