events {}

http {
    include /etc/nginx/mime.types;
    
    # Konfiguracja strefy cache z poprzedniego zadania
    proxy_cache_path /var/cache/nginx keys_zone=api_cache:10m;

    # NOWE: Blok upstream rozkładający ruch (domyślnie Round-Robin)
    upstream backend_cluster {
        server api-a:3000;
        server api-b:3000;
    }

    server {
        listen 80;
        root /usr/share/nginx/html;

        # Fallback dla aplikacji React SPA
        location / {
            try_files $uri /index.html;
        }

        # Cache'owany endpoint statystyk
        location ^~ /api/stats {
            proxy_cache api_cache;
            proxy_cache_valid 200 30s;
            add_header X-Cache-Status $upstream_cache_status;
            
            # Skierowanie ruchu do klastra
            proxy_pass http://backend_cluster/stats;
        }

        # Pozostałe zapytania do API (np. GET/POST /items)
        location /api/ {
            proxy_pass http://backend_cluster/;
        }
    }
}